### ISSUE TITLE
Maintenance and merge with similar plugin

### ISSUE THREAD

**Issue by heruan** [matjaz/aurelia-property-injection#3]
Hi @matjaz since I have developed a [similar plugin](https://github.com/heruan/aurelia-property-injection) for Aurelia, I'd like to know if you are actively maintaining this one, especially because I was trying to publish mine to NPM and I'd like to avoid confusion in the community with two plugins with the same name and functionality. Unfortunately I didn't know about yours and since you published it first, I will gladly adhere to your choice about this:
1. if you do not maintain this one anymore, let me publish mine to NPM under the same name;
2. if you will maintain this one and think mine is missing some functionality, we could merge the two;
3. if you simply don't want any of these, I'll find another name for mine and inform the community about the change.

You can find discussions on my plugin also at https://github.com/aurelia/dependency-injection/pull/85.

Thank you very much!

**Comment by matjaz** [comment]
I am definitely up to merge our projects, since they are really the same.

The key differences I see are:
My has support for
- properties in constructor
- `@inject` for all properties decorators*
- using Metadata.instanceActivator

Yours has support for
- additional decorators
- something else?

_*`@autoinject` is meant to be on class_

I am looking [into source](https://github.com/aurelia/dependency-injection/blob/master/src/container.js#L456) and see now there is support for `Metadata.invoker`. With that I think we can create properties injected in constructor.

Are you wiling to prepare PR to merge your functionality into mine package?

If we smoothen differences I am willing to add you as a maintainer of this package on npm.
Then, if there are no breaking changes we can release 0.4 otherwise 1.0.

**Comment by heruan** [comment]
Thank you @matjaz for your feedback! I developed the plugin with Aurelia's team supervision and the guidelines were:
1. not to mock with constructors (i.e. no property injection in the constructor);
2. ability to do property injection without decorators (i.e. the conventional `injectProperties`);
3. use different decorators for TS and non-TS files, so that `@inject` would always need the types whereas `@autoinject` wouldn't (all decorators are just the `aurelia-dependency-injection` ones extended to write the needed metadata).

Also, I'm leveraging the `Container. setHandlerCreatedCallback` hook as the way to extend `Container`'s features.

I guess a PR to stick with these guidelines would be a total rewrite. I can move my repository to a new organization and collaborate there, what do you think?

**Comment by matjaz** [comment]
1. `setHandlerCreatedCallback` is great, but does not allow for props in constructor.
   From my experience a lot of times I needed constructors just because of DI. `afterConstructor` is a good workaround however it feels clumsy especially if you also use `constructor`.
2. Totally agree with it.
3. ok, If Aurelia guys says so.

**Comment by matjaz** [comment]
Let's create new org. and collaborate there.
Please take a look at comments at https://github.com/aurelia/dependency-injection/pull/85#issuecomment-227723314

I am willing to move on with this.

**Comment by matjaz** [comment]
Published new version from https://github.com/devaur/aurelia-property-injection
